name: CI-Policy-Check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: validate
      uses: instrumenta/conftest-action@master
      with:
        files: aks.tf deployment.yaml



